PROJECT = the_scheduler

# -----------------------------------------------------------------------------
# GDB Settings
# -----------------------------------------------------------------------------
GDB_TOOL := $(shell command -v arm-none-eabi-gdb 2> /dev/null)
ifndef GDB_TOOL
GDB_TOOL := gdb-multiarch
endif

# -----------------------------------------------------------------------------
# QEMU Simulation Settings
# -----------------------------------------------------------------------------
ELF = $(PROJECT).elf
MACHINE = mps2-an386
# Note: QEMU uses 'cortex-m4' even if you are using the FPU (M4F)
CPU_QEMU = cortex-m4

# Flags: -nographic (no window), -serial mon:stdio (UART output to terminal)
QEMU_FLAGS = -M $(MACHINE) -cpu $(CPU_QEMU) -kernel $(ELF) -nographic -semihosting -monitor none -serial stdio
# Debug Flags: -S (freeze on startup), -s (listen on TCP 1234)
QEMU_FLAGS_DBG = -S -s

# -----------------------------------------------------------------------------
# Hardware & Architecture Settings
# -----------------------------------------------------------------------------

# Compiler definitions
CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

# Architecture flags
# MPS2-AN386 is a Cortex-M4
MCU_FLAGS = -mcpu=cortex-m4 -mthumb

# FPU Settings: Set to 1 for Cortex-M4F (Hardware FPU), 0 for Pure M4
USE_FPU = 1

ifeq ($(USE_FPU), 1)
    # Cortex-M4F (Hardware Floating Point)
    MCU_FLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
    PORT_DIR = FreeRTOS-Kernel/portable/GCC/ARM_CM4F
    # Define macros so code knows FPU is on
    USER_DEFINES = -DARM_MATH_CM4 -D__FPU_PRESENT=1
else
    # Cortex-M4 (Software Floating Point - "Pure M4")
    MCU_FLAGS += -mfloat-abi=soft
    PORT_DIR = FreeRTOS-Kernel/portable/GCC/ARM_CM3
endif

# -----------------------------------------------------------------------------
# Directories & Source Files
# -----------------------------------------------------------------------------

# Source Directories
KERNEL_DIR = FreeRTOS-Kernel
SOURCE_DIR = .
DEVICE_DIR = device
CONFIG_DIR = config
DRIVERS_DIR = drivers
UTILS_DIR   = utils

# Include Paths
INCLUDES = \
    -I$(SOURCE_DIR) \
    -I$(CONFIG_DIR) \
    -I$(KERNEL_DIR)/include \
    -I$(PORT_DIR) \
    -I$(DEVICE_DIR) \
    -I$(DRIVERS_DIR) \
    -I$(UTILS_DIR)

# Source Files
# 1. The Kernel
SOURCES = \
    $(KERNEL_DIR)/tasks.c \
    $(KERNEL_DIR)/queue.c \
    $(KERNEL_DIR)/list.c \
    $(KERNEL_DIR)/timers.c \
    $(KERNEL_DIR)/event_groups.c \
    $(KERNEL_DIR)/stream_buffer.c \
    $(PORT_DIR)/port.c

# 2. The Device Setup (Startup & Heap)
# Note: Using heap_4.c is standard for general use
SOURCES += \
    $(DEVICE_DIR)/startup_gcc.c \
    $(KERNEL_DIR)/portable/MemMang/heap_4.c

# 3. The Application
SOURCES += timeline_scheduler.c

USE_APP_MAIN ?= 1
ifeq ($(USE_APP_MAIN),1)
SOURCES += main.c \
           $(EXTRA_SOURCES)
endif

#this is for mainly testing
EXTRA_SOURCES ?=
SOURCES += $(EXTRA_SOURCES)

# 4. Project Modules (drivers/ and utils/)
DRIVERS_SRCS := $(wildcard $(DRIVERS_DIR)/*.c)
UTILS_SRCS   := $(wildcard $(UTILS_DIR)/*.c)
SOURCES += $(DRIVERS_SRCS) $(UTILS_SRCS)

DRIVERS_OBJS := $(DRIVERS_SRCS:.c=.o)
UTILS_OBJS   := $(UTILS_SRCS:.c=.o)

# -----------------------------------------------------------------------------
# Compiler Flags
# -----------------------------------------------------------------------------

#added -w to remove warning (but remember to remove it, warnings should be fixed)
CFLAGS = $(MCU_FLAGS) $(INCLUDES) \
    -O0 -g3 -w -Wall -Wextra \
    -ffunction-sections -fdata-sections \
    $(USER_DEFINES)

LDFLAGS = $(MCU_FLAGS) \
    -T$(DEVICE_DIR)/mps2_an386.ld \
    -Wl,--gc-sections \
    -Wl,-Map=$(PROJECT).map \

# -----------------------------------------------------------------------------
# Build Rules
# -----------------------------------------------------------------------------

# Object files (autogenerated list)
OBJS = $(SOURCES:.c=.o)

all: $(PROJECT).elf

$(PROJECT).elf: $(OBJS)
	@echo "Linking..."
	$(CC) $(OBJS) $(LDFLAGS) -o $@
	$(SIZE) $@

%.o: %.c
	@echo "Compiling $<..."
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(PROJECT).elf $(PROJECT).map

# -----------------------------------------------------------------------------
# Simulation Rules
# -----------------------------------------------------------------------------

# Run the simulation (Press Ctrl+A, then X to exit)
qemu: all
	@echo "Starting QEMU..."
	qemu-system-arm $(QEMU_FLAGS)

# Start simulation in "Frozen" state waiting for GDB
qemu_debug: all
	@echo "Starting QEMU in debug mode (Waiting for GDB on :1234)..."
	qemu-system-arm $(QEMU_FLAGS) $(QEMU_FLAGS_DBG)

# Start GDB and connect to QEMU automatically
gdb:
	$(GDB_TOOL) $(ELF) -ex "target remote localhost:1234"

.PHONY: all clean qemu qemu_debug gdb drivers utils
