PROJECT = the_scheduler

# -----------------------------------------------------------------------------
# Hardware & Architecture Settings
# -----------------------------------------------------------------------------

# Compiler definitions
CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

# Architecture flags
# MPS2-AN386 is a Cortex-M4
MCU_FLAGS = -mcpu=cortex-m4 -mthumb

# FPU Settings: Set to 1 for Cortex-M4F (Hardware FPU), 0 for Pure M4
USE_FPU = 1

ifeq ($(USE_FPU), 1)
    # Cortex-M4F (Hardware Floating Point)
    MCU_FLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
    PORT_DIR = FreeRTOS-Kernel/portable/GCC/ARM_CM4F
    # Define macros so code knows FPU is on
    USER_DEFINES = -DARM_MATH_CM4 -D__FPU_PRESENT=1
else
    # Cortex-M4 (Software Floating Point - "Pure M4")
    MCU_FLAGS += -mfloat-abi=soft
    PORT_DIR = FreeRTOS-Kernel/portable/GCC/ARM_CM3
endif

# -----------------------------------------------------------------------------
# Directories & Source Files
# -----------------------------------------------------------------------------

# Source Directories
KERNEL_DIR = FreeRTOS-Kernel
SOURCE_DIR = .
DEVICE_DIR = device
CONFIG_DIR = config

# Include Paths
INCLUDES = \
    -I$(SOURCE_DIR) \
    -I$(CONFIG_DIR) \
    -I$(KERNEL_DIR)/include \
    -I$(PORT_DIR) \
    -I$(DEVICE_DIR)

# Source Files
# 1. The Kernel
SOURCES = \
    $(KERNEL_DIR)/tasks.c \
    $(KERNEL_DIR)/queue.c \
    $(KERNEL_DIR)/list.c \
    $(KERNEL_DIR)/timers.c \
    $(KERNEL_DIR)/event_groups.c \
    $(KERNEL_DIR)/stream_buffer.c \
    $(PORT_DIR)/port.c

# 2. The Device Setup (Startup & Heap)
# Note: Using heap_4.c is standard for general use
SOURCES += \
    $(DEVICE_DIR)/startup_gcc.c \
    $(KERNEL_DIR)/portable/MemMang/heap_4.c

# 3. The Application
SOURCES += main.c 

# -----------------------------------------------------------------------------
# Compiler Flags
# -----------------------------------------------------------------------------

CFLAGS = $(MCU_FLAGS) $(INCLUDES) \
    -O0 -g3 -Wall -Wextra \
    -ffunction-sections -fdata-sections \
    $(USER_DEFINES)

LDFLAGS = $(MCU_FLAGS) \
    -T$(DEVICE_DIR)/mps2_an386.ld \
    -Wl,--gc-sections \
    -Wl,-Map=$(PROJECT).map \

# -----------------------------------------------------------------------------
# Build Rules
# -----------------------------------------------------------------------------

# Object files (autogenerated list)
OBJS = $(SOURCES:.c=.o)

all: $(PROJECT).elf

$(PROJECT).elf: $(OBJS)
	@echo "Linking..."
	$(CC) $(OBJS) $(LDFLAGS) -o $@
	$(SIZE) $@

%.o: %.c
	@echo "Compiling $<..."
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(PROJECT).elf $(PROJECT).map

.PHONY: all clean
